@startuml
package "Cooking on Fire" {
  interface HTTP as H1
  interface HTTP as H2
  interface HTTP as H3
  [hapi-fhir-jpaserver-base] -u- H1
  [cooking-on-fire-backend] -u- H2
  [cooking-on-fire-frontend]
  [cooking-on-fire-backend] --> () H1
  [cooking-on-fire-frontend] --> () H2
  [cooking-on-fire-backend] -r-> () H3
  H3 - [elastic-search]
}
interface OAuth2 as O2
[cooking-on-fire-frontend] -r-> () O2
O2 - [IAM]
note right of [IAM]
  e.g. Google Single Sign-in
end note
@enduml
